name: Python CI

# Trigger the workflow on any push to the main branch or pull request
#We can run events on the git like push,pull,merge , and delete

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  test:
    runs-on: ubuntu-latest #run on the ubuntu containers #Jobs will be run on the py

    steps:
      # Step 1: Check out the code from the repository
      - name: Check out code
        uses: actions/checkout@v2 #the versions may change based on the actions

      # Step 2: Set up Python environment
      - name: Set up Python
        uses: actions/setup-python@v2 #this is developed with python-versiom
        with:
          python-version: '3.8'

      # Step 3: Install dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # Step 4: Run tests
      - name: Run tests
        run: pytest
